featuredImageField: image
rssFullContent: true
favicon: "https://joaquindecima.gitlab.io/android-chrome-512x512.png"
description: Hola, Soy Pato, un apasionado por la tecnología y el desarrollo de software. Me encanta aprender y compartir mis conocimientos con la comunidad. En este espacio, encontrarás recursos, tutoriales y proyectos relacionados con la programación, la informática y el mundo de GNU/Linux. ¡Espero que disfrutes de tu visita! Si tienes alguna pregunta o sugerencia, no dudes en contactarme. Estoy aquí para ayudarte y aprender juntos. ¡Gracias por visitar mi sitio web!

community:
  enabled: true
  title: Comunidad
  description: Unite a nuestro Grupo de Telegram
  url: https://t.me/PatoJADCommunity
  text: Unirme
  image: https://i.postimg.cc/nrMm8KP2/comunidad.webp

footer:
  social:
    - identifier: telegram
      name: Comunidad Telegram
      url: https://t.me/PatoJADCommunity
      weight: 1
      params:
        icon: fab fa-telegram
        color: "#0088cc"
    - identifier: youtube
      name: Youtube
      url: https://www.youtube.com/channel/UCta4Iy4TzMx8Xo0pwpkbWgg
      weight: 2
      params:
        icon: fab fa-youtube
        color: "#FF0000"
    - identifier: instagram
      name: Instagram
      url: https://www.instagram.com/patojadoficial/
      weight: 3
      params:
        icon: fab fa-instagram
        color: "#E4405F"
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/PatoJADOficial
      weight: 4
      params:
        icon: fab fa-twitter
        color: "#1DA1F2"
    - identifier: facebook
      name: Facebook
      url: https://www.facebook.com/PatoJAD/
      weight: 5
      params:
        icon: fab fa-facebook
        color: "#1877F2"
    - identifier: twitch
      name: Twitch
      url: https://www.twitch.tv/patojad
      weight: 6
      params:
        icon: fab fa-twitch
        color: "#6441A4"
    - identifier: tiktok
      name: TikTok
      url: https://www.tiktok.com/@patojadoficial
      weight: 7
      params:
        icon: fab fa-tiktok
        color: "#69C9D0"
    - identifier: whatsapp
      name: WhatsApp
      url: https://whatsapp.com/channel/0029VaJ9UV9FnSzBSJLZxg3A
      weight: 8
      params:
        icon: fab fa-whatsapp
        color: "#25D366"

dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST

article:
  math: true
  toc: true
  readingTime: true

comments:
  enabled: false

opengraph:
  twitter:
    # Your Twitter username
    site: PatoJADOficial

    # Available values: summary, summary_large_image
    card: summary_large_image

defaultImage:
  enabled: true
  local: true
  src: img/profile.jpeg

colorScheme:
  # Display toggle
  toggle: true

  # Available values: auto, light, dark
  default: auto

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

donate:
  enabled: true
  title: Apoyame
  main:
    - identifier: paypal
      name: Paypal
      url: https://paypal.me/joaquindecima
      weight: 1
      params:
        icon: fab fa-paypal
        is_crypto: false
        color: "#003087"
    - identifier: amazon
      name: Amazon
      url: https://www.amazon.com/hz/wishlist/ls/3BFB7DGU3ERLO?ref_=wl_share
      weight: 2
      params:
        icon: fab fa-amazon
        is_crypto: false
        color: "#FF9900"
    - identifier: mercadopago
      name: MP
      url: https://link.mercadopago.com.ar/joaquindecima
      weight: 3
      params:
        icon: fas fa-handshake
        is_crypto: false
        color: "#0038A8"
    - identifier: bitcoin
      name: Bitcoin
      url: bc1qjedvfvz6h9d0rjp2mz70y90mylpx8hr52fcmsp
      weight: 4
      params:
        icon: fab fa-bitcoin
        is_crypto: true
        color: "#F7931A"
    - identifier: usdt
      name: Ethereum
      url: 0xF3f0B0CdaF01C68E4D64c2Ad3A703aBe252278EB
      weight: 5
      params:
        icon: fab fa-ethereum
        is_crypto: true
        color: "#26A17B"

social:
  enabled: true
  title: Redes Sociales
  main:
    - identifier: telegram
      name: Comunidad Telegram
      url: https://t.me/PatoJADCommunity
      weight: 1
      params:
        icon: fab fa-telegram
        color: "#0088cc"
    - identifier: youtube
      name: Youtube
      url: https://www.youtube.com/channel/UCta4Iy4TzMx8Xo0pwpkbWgg
      weight: 2
      params:
        icon: fab fa-youtube
        color: "#FF0000"
    - identifier: instagram
      name: Instagram
      url: https://www.instagram.com/patojadoficial/
      weight: 3
      params:
        icon: fab fa-instagram
        color: "#E4405F"
    - identifier: mastodon
      name: Mastodon
      url: https://mastodon.social/@PatoJAD
      weight: 4
      params:
        icon: fab fa-mastodon
        color: "#6364A7"
    - identifier: tgblog
      name: Canal Telegram
      url: https://t.me/PatoJADBlog
      weight: 5
      params:
        icon: fas fa-bullhorn
        color: "#333333"
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/PatoJADOficial
      weight: 6
      params:
        icon: fab fa-twitter
        color: "#1DA1F2"
    - identifier: facebook
      name: Facebook
      url: https://www.facebook.com/PatoJAD/
      weight: 7
      params:
        icon: fab fa-facebook
        color: "#1877F2"
    - identifier: steam
      name: Steam
      url: https://steamcommunity.com/id/joaquindecima/
      weight: 9
      params:
        icon: fab fa-steam
        color: "#00ADEE"
    - identifier: twitch
      name: Twitch
      url: https://www.twitch.tv/patojad
      weight: 10
      params:
        icon: fab fa-twitch
        color: "#6441A4"
    - identifier: linkedin
      name: Linkedin
      url: https://linkedin.com/in/joaquindecima
      weight: 10
      params:
        icon: fab fa-linkedin
        color: "#0A66C2"
    - identifier: github
      name: GitHub
      url: https://github.com/JoaquinDecima
      weight: 10
      params:
        icon: fab fa-github
        color: "#181717"
    - identifier: gitlab
      name: GitLab
      url: https://gitlab.com/joaquindecima
      weight: 10
      params:
        icon: fab fa-gitlab
        color: "#FC6D26"
    - identifier: tiktok
      name: TikTok
      url: https://www.tiktok.com/@patojadoficial
      weight: 10
      params:
        icon: fab fa-tiktok
        color: "#00f2ea"
    - identifier: whatsapp
      name: WhatsApp
      url: https://whatsapp.com/channel/0029VaJ9UV9FnSzBSJLZxg3A
      weight: 10
      params:
        icon: fab fa-whatsapp
        color: "#25D366"

friendsSite:
  enabled: true
  title: Sitios Amigos
  main:
    - identifier: Proyecto Tic Tac
      name: Proyecto Tic Tac
      url: https://proyectotictac.com/
      image: https://i.postimg.cc/gj8TY4vm/proyectotictac.webp
    - identifier: Jona3717
      name: Jona3717
      url: https://jona3717.gitlab.io/
      image: https://i.postimg.cc/m2WndfsD/jona3717.webp
    - identifier: Vasak OS
      name: Vasak OS
      url: https://os.vasak.net.ar/
      image: https://os.vasak.net.ar/img/logo.svg
    - identifier: CuerdOS Linux
      name: CuerdOS Linux
      url: https://cuerdos.github.io/
      image: https://cuerdos.github.io/Frontend/src/Images/cuerdos_logo.webp
    - identifier: El Tao del Hacking
      name: El Tao del Hacking
      url: https://www.eltaodelhacking.com/
      image: https://i.postimg.cc/tJ6sgXdT/Bb9dg1-WN-400x400.webp
    - identifier: CallMe Zatiel
      name: CallMe Zatiel
      url: https://www.youtube.com/c/CallMeZatiel
      image: https://i.postimg.cc/8z10SRsg/zatiel.webp
    - identifier: ZatielFX
      name: ZatielFX
      url: https://www.youtube.com/c/ZatielFX
      image: https://i.postimg.cc/cJz9wPhd/zatiel2.webp
    - identifier: Alexia
      name: Alexia
      url: https://lexi.lat/
      image: https://lexi.lat/assets/img/peach.gif
    - identifier: Salmorejo Geek
      name: Salmorejo Geek
      url: https://salmorejogeek.com/
      image: https://salmorejogeek.com/wp-content/uploads/2020/11/cropped-salmorejo-geek-v2-300px.png?w=200
    - identifier: Last Dragon
      name: Last Dragon
      url: https://www.lastdragon.net/
      image: https://i.postimg.cc/13Z59j7h/last-dragon.jpg
    - identifier: Codigo Cristo
      name: Codigo Cristo
      url: https://codigocristo.github.io/
      image: https://codigocristo.github.io/img/logo.png
    - identifier: Tano Marcelo
      name: Tano Marcelo
      url: https://tano.codeberg.page/
      image: https://i.postimg.cc/6Q8zWYXg/tano.webp

technologies:
  enabled: true
  title: Tecnologias
  main:
    - identifier: JavaScript
      name: JavaScript
      url: https://developer.mozilla.org/es/docs/Web/JavaScript
      image: https://cdn.svglogos.dev/logos/javascript.svg
    - identifier: HTML
      name: HTML
      url: https://developer.mozilla.org/es/docs/Web/HTML
      image: https://cdn.svglogos.dev/logos/html-5.svg
    - identifier: CSS
      name: CSS
      url: https://developer.mozilla.org/es/docs/Web/CSS
      image: https://cdn.svglogos.dev/logos/css-3.svg
    - identifier: TypeScript
      name: TypeScript
      url: https://www.typescriptlang.org/
      image: https://cdn.svglogos.dev/logos/typescript-icon.svg
    - identifier: PHP
      name: PHP
      url: https://www.php.net/
      image: https://cdn.svglogos.dev/logos/php.svg
    - identifier: Node.js
      name: Node.js
      url: https://nodejs.org/
      image: https://cdn.svglogos.dev/logos/nodejs-icon-alt.svg
    - identifier: Bun
      name: Bun
      url: https://bun.sh/
      image: https://cdn.svglogos.dev/logos/bun.svg
    - identifier: Python
      name: Python
      url: https://www.python.org/
      image: https://cdn.svglogos.dev/logos/python.svg
    - identifier: Vite
      name: Vite
      url: https://vitejs.dev/
      image: https://cdn.svglogos.dev/logos/vitejs.svg
    - identifier: Vue.js
      name: Vue.js
      url: https://vuejs.org/
      image: https://cdn.svglogos.dev/logos/vue.svg
    - identifier: Astro
      name: Astro
      url: https://astro.build/
      image: https://cdn.svglogos.dev/logos/astro-icon.svg
    - identifier: Angular
      name: Angular
      url: https://angular.dev/
      image: https://cdn.svglogos.dev/logos/angular-icon.svg
    - identifier: React
      name: React
      url: https://react.dev/
      image: https://cdn.svglogos.dev/logos/react.svg
    - identifier: Nest.js
      name: Nest.js
      url: https://nestjs.com/
      image: https://cdn.svglogos.dev/logos/nestjs.svg
    - identifier: Laravel
      name: Laravel
      url: https://laravel.com/
      image: https://cdn.svglogos.dev/logos/laravel.svg  
    - identifier: Tauri
      name: Tauri
      url: https://tauri.app/
      image: https://cdn.svglogos.dev/logos/tauri.svg
    - identifier: JWT 
      name: JSON Web Token
      url: https://jwt.io/
      image: https://cdn.svglogos.dev/logos/jwt-icon.svg
    - identifier: MongoDB
      name: MongoDB
      url: https://www.mongodb.com/
      image: https://cdn.svglogos.dev/logos/mongodb-icon.svg
    - identifier: MariaDB
      name: MariaDB
      url: https://www.mariadb.org/
      image: https://cdn.svglogos.dev/logos/mariadb-icon.svg
    - identifier: MySQL
      name: MySQL
      url: https://mariadb.org/
      image: https://cdn.svglogos.dev/logos/mysql-icon.svg
    - identifier: hugo
      name: Hugo
      url: https://gohugo.io/
      image: https://cdn.svglogos.dev/logos/hugo.svg
    - identifier: WordPress
      name: WordPress
      url: https://wordpress.org/
      image: https://cdn.svglogos.dev/logos/wordpress-icon-alt.svg
    - identifier: Tailwind CSS
      name: Tailwind CSS
      url: https://tailwindcss.com/
      image: https://cdn.svglogos.dev/logos/tailwindcss-icon.svg
    - identifier: Bootstrap
      name: Bootstrap
      url: https://getbootstrap.com/
      image: https://cdn.svglogos.dev/logos/bootstrap.svg
    - identifier: Git
      name: Git
      url: https://git-scm.com/
      image: https://cdn.svglogos.dev/logos/git-icon.svg
    - identifier: github
      name: GitHub
      url: https://github.com/JoaquinDecima
      image: https://cdn.svglogos.dev/logos/github-octocat.svg
    - identifier: gitlab
      name: GitLab
      url: https://gitlab.com/joaquindecima
      image: https://cdn.svglogos.dev/logos/gitlab.svg
    - identifier: Google Search Console
      name: Google Search Console
      url: https://search.google.com/search-console
      image: https://cdn.svglogos.dev/logos/google-search-console.svg
    - identifier: Swagger
      name: Swagger
      url: https://swagger.io/
      image: https://cdn.svglogos.dev/logos/swagger.svg
    - identifier: Jira
      name: Jira
      url: https://www.atlassian.com/es/software/jira
      image: https://cdn.svglogos.dev/logos/jira.svg
    - identifier: Confluence
      name: Confluence
      url: https://www.atlassian.com/es/software/confluence
      image: https://cdn.svglogos.dev/logos/confluence.svg
    - identifier: Asana
      name: Asana
      url: https://asana.com/
      image: https://cdn.svglogos.dev/logos/asana-icon.svg
    - identifier: Trello
      name: Trello
      url: https://trello.com/
      image: https://cdn.svglogos.dev/logos/trello.svg
    - identifier: Taiga
      name: Taiga
      url: https://taiga.io/
      image: https://cdn.svglogos.dev/logos/taiga.svg
    - identifier: Cloudflare
      name: Cloudflare
      url: https://www.cloudflare.com/
      image: https://cdn.svglogos.dev/logos/cloudflare-icon.svg
    - identifier: AWS
      name: AWS
      url: https://aws.amazon.com/
      image: https://cdn.svglogos.dev/logos/aws.svg
    - identifier: Azure
      name: Azure
      url: https://azure.microsoft.com/
      image: https://cdn.svglogos.dev/logos/microsoft-azure.svg
    - identifier: Docker
      name: Docker
      url: https://www.docker.com/
      image: https://cdn.svglogos.dev/logos/docker-icon.svg
    - identifier: Nginx
      name: Nginx
      url: https://www.nginx.com/
      image: https://cdn.svglogos.dev/logos/nginx.svg
    - identifier: XAMPP
      name: XAMPP
      url: https://www.apachefriends.org/es/index.html
      image: https://cdn.svglogos.dev/logos/xampp.svg
    - identifier: Linux
      name: Linux
      url: https://www.linux.org/
      image: https://cdn.svglogos.dev/logos/linux-tux.svg
    - identifier: Ubuntu
      name: Ubuntu
      url: https://ubuntu.com/
      image: https://cdn.svglogos.dev/logos/ubuntu.svg
    - identifier: Debian
      name: Debian
      url: https://www.debian.org/
      image: https://cdn.svglogos.dev/logos/debian.svg
    - identifier: Almalinux
      name: AlmaLinux
      url: https://almalinux.org/
      image: https://upload.wikimedia.org/wikipedia/commons/e/ec/AlmaLinux_Icon_Logo.png
    - identifier: Arch Linux
      name: Arch Linux
      url: https://archlinux.org/
      image: https://cdn.svglogos.dev/logos/archlinux.svg
    - identifier: Windows
      name: Windows
      url: https://www.microsoft.com/es-es/windows/
      image: https://cdn.svglogos.dev/logos/microsoft-windows-icon.svg
    - identifier: MacOS
      name: MacOS
      url: https://www.apple.com/es/macos/
      image: https://cdn.svglogos.dev/logos/apple.svg
